# These are supported funding model platforms

github: [f22raptorroland,dovedescent7,xavier-thomas,PrutzerNL]
patreon: PeterSuh-Q3
buy_me_a_coffee: PeterSuh-Q3
custom: ["https://paypal.me/PeterSuhQ3"]
